# ddu
[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_source = 'denops.vim'
hook_add = '''
noremap <Leader>o <Cmd>Ddu file_rec<CR>
noremap <Leader>b <Cmd>Ddu buffer<CR>
'''
hook_source = '''
call ddu#custom#patch_global({
    \ 'ui': 'ff',
    \ 'uiParams': {
    \   'ff': {
    \     'split': 'floating',
    \     'startFilter': v:true,
    \     'floatingBorder': 'single',
    \    },
    \ },
    \ 'sources': [
    \   {'name': 'file', 'params': {}},
    \   {'name': 'register'},
    \   {'name': 'buffer'},
    \ ],
    \ 'sourceOptions': {
    \   '_': {
    \     'matchers': ['matcher_substring'],
    \   },
    \ },
    \ 'kindOptions': {
    \   'file': {
    \     'defaultAction': 'open',
    \   },
    \   'buffer': {
    \     'defaultAction': 'open',
    \   },
    \ },
    \ })
autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR>    <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space> <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i       <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> q       <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  nnoremap <buffer><silent> <C-n>   j
  nnoremap <buffer><silent> <C-p>   k
endfunction
autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR>    <Esc><Cmd>close<CR>
  nnoremap <buffer><silent> <CR>    <Cmd>close<CR>
  nnoremap <buffer><silent> q       <Cmd>close<CR>
endfunction
'''

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-filter'
on_source = 'ddu.vim'
[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-register'
on_source = 'ddu.vim'


[[plugins]]
repo = 'shun/ddu-source-buffer'
on_source = 'ddu.vim'


[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

