[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'YHiroyuki/atea'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'romainl/Apprentice'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  set updatetime=500
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

# Go言語用
[[plugins]]
repo = 'fatih/vim-go'
[[plugins]]
repo = 'vim-jp/vim-go-extra'

# tomlファイル
[[plugins]]
repo = 'cespare/vim-toml'
