[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'CursorHold'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

# 補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
autocmd CompleteDone * silent! pclose!
set completeopt+=noinsert
imap <C-Space> <C-x><C-o>
'''
hook_source = '''
call deoplete#custom#option('smart_case', v:true)
'''

[[plugins]]
repo = 'akinsho/bufferline.nvim'
on_i=1
hook_source = '''
set termguicolors
lua require"bufferline".setup()
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_i=1
hook_source = '''
  let g:lexima_enable_space_rules = 0
  call lexima#add_rule({'char': '（', 'input_after': '）'})
  call lexima#add_rule({'char': '<BS>', 'at': '（\%#）', 'delete': 1})
'''
