# ステータスバーのカスタマイズ
# インデントの表示
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
  let g:indentLine_fileTypeExclude = ['help', 'nerdtree', 'vimfiler', 'defx']
  let g:indentLine_char = '│'
'''

# 単語検索
[[plugins]]
repo = 'mileszs/ack.vim'

# 整形
[[plugins]]
repo = 'kg8m/vim-simple-align'

# コーディングスタイル調整
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# Git関連
[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
lua_add = '''
require('gitsigns').setup {
  signcolumn = false,
  numhl = true,
  linehl = false,
  word_diff = false,
}
'''

# tomlファイル
[[plugins]]
repo = 'cespare/vim-toml'

# アイコン
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'Shougo/pum.vim'

# 翻訳
[[plugins]]
repo = 'skanehira/translate.vim'
hook_add = '''
  let g:translate_source = "en"
  let g:translate_target = "ja"
  let g:translate_popup_window = 1
  let g:translate_winsize = 3
'''

[[plugins]]
 repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason.nvim'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'


[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
lua_add = '''
require('plugins.lualine')
'''
